AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Frontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aiofeed.com
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
  FrontendPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Frontend
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Join ["", [!GetAtt Frontend.Arn, "/*"]]
            Principal: "*"
