AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Frontend:
    Properties:
      AccessControl: PublicRead
      BucketName: notifies.mambans.com
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
