version: 0.2

env:
  variables:
    CI: 'true'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "-Start Phase Install at `date`-"
      - npm i -g npm@7
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - ./aws/install
      # - rm -rf aws awscliv2.zip
      - npm ci --prefix ./frontend
      - echo "-End Phase Install at `date`-"
  pre_build:
    commands:
      - echo "-Phase pre_build- at `date`"
      - npm run test --prefix ./frontend
      - echo "-End Phase pre_build- at `date`"
  build:
    commands:
      - echo "Start -Phase build- at `date`"
      - npm run cleanup --prefix ./frontend
      - npm run push --prefix ./frontend
      - echo "End -Phase build- at `date`"
  post_build:
    commands:
      - echo "-Phase post_build-"
