AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
    EndpointConfiguration: REGIONAL
Resources:
  Create:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Create an AioFeed account with tokens and monitored vod channels
        default to null and empty array.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/create
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.email:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: create/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  DeleteAccount:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Delete an account
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: delete
            Path: /account/delete
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: deleteAccount/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  FetchMonitoredChannels:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Fetch monitored vod channels list.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: get
            Path: /monitored-channels/fetch
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.authkey:
                Required: true
          Type: Api
      Handler: monitoredChannelsFetch/handler.handler
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  Login:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Login with AioFeed account and return account info, tokens and
        monitored vod channels.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/login
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: login/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ReAuthenticateTwitch:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Re-authenticate Twitch user with Twitch (returns access & refresh
        tokens).
      Environment:
        Variables:
          TWITCH_CLIENT_ID: TWITCH_CLIENT_ID
          TWITCH_CLIENT_SECRET: TWITCH_CLIENT_SECRET
      Events:
        Http:
          Properties:
            Method: put
            Path: /reauth/twitch
          RequestParameters:
          - method.request.querystring.refresh_token:
              Required: true
          Type: Api
      Handler: reAuthenticateTwitch/handler.handler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  RequestTwitchTokens:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Re-authenticate Twitch user with Twitch (returns access & refresh
        tokens).
      Environment:
        Variables:
          TWITCH_CLIENT_ID: TWITCH_CLIENT_ID
          TWITCH_CLIENT_SECRET: TWITCH_CLIENT_SECRET
      Events:
        Http:
          Properties:
            Method: put
            Path: /rerequest/twitch
          RequestParameters:
          - method.request.querystring.authCode:
              Required: true
          Type: Api
      Handler: requestTwitchTokens/handler.handler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  Update:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Update a specific column mentioned as a param.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /account/update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.columnValue:
              Required: true
          - method.request.querystring.columnName:
              Required: true
          Type: Api
      Handler: update/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UpdateMonitoredChannels:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Update monitored vod channels list.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /monitored-channels/update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.channels:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: monitoredChannelsUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UpdatePreferences:
    Properties:
      CodeUri: s3://aiofeed-backend/adfdf685298c9933f88225d748c28deb
      Description: Update preferences for mentioned data name/type.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /account/preferences
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.dataName:
              Required: true
          - method.request.querystring.data:
              Required: true
          Type: Api
      Handler: updateStoredPreferences/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UserLogins:
    Properties:
      AttributeDefinitions:
      - AttributeName: Username
        AttributeType: S
      KeySchema:
      - AttributeName: Username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
