AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''https://aiofeed.com'''
    EndpointConfiguration: REGIONAL
  Function:
    CodeUri: .
    Runtime: nodejs10.x
Resources:
  AppInfo:
    Properties:
      AttributeDefinitions:
      - AttributeName: Name
        AttributeType: S
      KeySchema:
      - AttributeName: Name
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  Create:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Create an AioFeed account with tokens and monitored vod channels
        default to null and empty array.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/create
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.email:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: create/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  DeleteAccount:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Delete an account
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: delete
            Path: /account
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.password:
                Required: true
            - method.request.querystring.authkey:
                Required: true
          Type: Api
      Handler: deleteAccount/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  DeleteSavedLists:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Delete custom saved lists.
      Environment:
        Variables:
          SAVED_LISTS:
            Ref: SavedLists
      Events:
        Http:
          Properties:
            Method: put
            Path: /savedlists/delete
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.listName:
              Required: true
          Type: Api
      Handler: savedListsDelete/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: SavedLists
    Type: AWS::Serverless::Function
  DeleteTwitchData:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Deletes all Twitch data associated with the account.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: delete
            Path: /twitch/token
          RequestParameters:
          - method.request.querystring.authkey:
              Required: true
          - method.request.querystring.username:
              Required: true
          Type: Api
      Handler: DeleteTwitchData/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  DeleteYotubeData:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Delete all Youtube data associated with the account.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: delete
            Path: /youtube/token
          RequestParameters:
          - method.request.querystring.authkey:
              Required: true
          - method.request.querystring.username:
              Required: true
          Type: Api
      Handler: DeleteYoutubeData/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  FetchSavedLists:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Fetch custom saved lists.
      Environment:
        Variables:
          SAVED_LISTS:
            Ref: SavedLists
      Events:
        Http:
          Properties:
            Method: get
            Path: /savedlists
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          Type: Api
      Handler: savedListsFetch/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: SavedLists
    Type: AWS::Serverless::Function
  Login:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Login with AioFeed account and return account info, tokens and
        monitored vod channels.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/login
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: login/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  PreferencesFetchAll:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Fetch all preferences.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: get
            Path: /preferences
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.authkey:
                Required: true
          Type: Api
      Handler: preferencesFetchAll/handler.handler
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  ReAuthenticateTwitch:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Re-authenticate Twitch user to Twitch with refresh token (returns
        access & refresh tokens).
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /reauth/twitch
          RequestParameters:
          - method.request.querystring.refresh_token:
              Required: true
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: reAuthenticateTwitch/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  RequestTwitchTokens:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Re-authenticate Twitch user to Twitch with authorization code (returns
        access & refresh tokens).
      Events:
        Http:
          Properties:
            Method: put
            Path: /rerequest/twitch
          RequestParameters:
          - method.request.querystring.authCode:
              Required: true
          Type: Api
      Handler: requestTwitchTokens/handler.handler
    Type: AWS::Serverless::Function
  SavedLists:
    Properties:
      AttributeDefinitions:
      - AttributeName: Username
        AttributeType: S
      KeySchema:
      - AttributeName: Username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  SoftUpdate:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Update a specific column mentioned as a param but merge it with
        its current value.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /account/soft-update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.columnValue:
              Required: true
          - method.request.querystring.columnName:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: softUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  Update:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Update a specific column mentioned as a param.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /account/update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.columnValue:
              Required: true
          - method.request.querystring.columnName:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: update/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  UpdateNotisChannelsUpdate:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Update channel list (channels with updated title/game notifications
        enabled.).
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /updatechannels
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.channels:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: updateNotisChannelsUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  UpdateSavedLists:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Update custom saved lists.
      Environment:
        Variables:
          SAVED_LISTS:
            Ref: SavedLists
      Events:
        Http:
          Properties:
            Method: put
            Path: /savedlists
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.videosObj:
              Required: true
          - method.request.querystring.listName:
              Required: true
          Type: Api
      Handler: savedListsUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: SavedLists
    Type: AWS::Serverless::Function
  UserLogins:
    Properties:
      AttributeDefinitions:
      - AttributeName: Username
        AttributeType: S
      KeySchema:
      - AttributeName: Username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
  VodChannelsUpdate:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Update monitored vod channels list.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /vodchannels
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.channels:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: vodChannelsUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
  YoutubeFetchTokens:
    Properties:
      CodeUri: s3://aiofeed-backend/795c27d97c2f6ea51c423211f17241c3
      Description: Exchange an authorization code for an access and refresh token
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /youtube/token
          RequestParameters:
          - method.request.querystring.authCode: null
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.authkey:
              Required: true
          Type: Api
      Handler: YoutubeFetchTokens/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
