AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
    EndpointConfiguration: REGIONAL
Resources:
  Create:
    Properties:
      CodeUri: s3://rp-deployment/6bfc26ec02deb483b964884f41e256fb
      Description: Create an Notifies account with tokens and monitored vod channels
        default to null and empty array.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/create
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.email:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: create/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  Login:
    Properties:
      CodeUri: s3://rp-deployment/6bfc26ec02deb483b964884f41e256fb
      Description: Login with Notifies account and return account info, tokens and
        monitored vod channels.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: post
            Path: /account/login
            RequestParameters:
            - method.request.querystring.username:
                Required: true
            - method.request.querystring.password:
                Required: true
          Type: Api
      Handler: login/handler.handler
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  Update:
    Properties:
      CodeUri: s3://rp-deployment/6bfc26ec02deb483b964884f41e256fb
      Description: Update a specific token mentioned as a param.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /account/update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.token:
              Required: true
          - method.request.querystring.tokenName:
              Required: true
          Type: Api
      Handler: update/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UpdateMonitoredChannels:
    Properties:
      CodeUri: s3://rp-deployment/6bfc26ec02deb483b964884f41e256fb
      Description: Update monitored vod channels list.
      Environment:
        Variables:
          USERNAME_TABLE:
            Ref: UserLogins
      Events:
        Http:
          Properties:
            Method: put
            Path: /monitored-channels/update
          RequestParameters:
          - method.request.querystring.username:
              Required: true
          - method.request.querystring.channels:
              Required: true
          Type: Api
      Handler: monitoredChannelsUpdate/handler.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserLogins
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UserLogins:
    Properties:
      AttributeDefinitions:
      - AttributeName: Username
        AttributeType: S
      KeySchema:
      - AttributeName: Username
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
